version: '3'

services:
  db:
    container_name: db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "9906:3306"  

  php-apache:
    container_name: php-apache
    build: php-apache/
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/apache2/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - .logs/apache:/var/log/apache2
    links:
      - db

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./src:/usr/share/nginx/html
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - 8000:80
    links:
      - php-apache
      - db

volumes:
  db_volume:
